"""refactor product inventory structure

Revision ID: 26d1f5996ba9
Revises: 4eb799e3b350
Create Date: 2026-08-12 15:00:59.690427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d1f5996ba9'
down_revision: Union[str, Sequence[str], None] = '4eb799e3b350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_product_warehouse')
    )
    op.create_index(op.f('ix_inventory_stock_id'), 'inventory_stock', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_product_id'), 'inventory_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_warehouse_id'), 'inventory_stock', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('products_warehouse_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'location')
    op.drop_column('products', 'warehouse_id')
    op.drop_column('products', 'minimum_stock_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('minimum_stock_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_warehouse_id_fkey'), 'products', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_index(op.f('ix_inventory_stock_warehouse_id'), table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_product_id'), table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_id'), table_name='inventory_stock')
    op.drop_table('inventory_stock')
    # ### end Alembic commands ###
